test_run = require('test_run').new()
---
...
vshard = require('vshard')
---
...
lerror = vshard.error
---
...
--
-- Test string representations of errors.
--
ok, err = pcall(box.error, box.error.TIMEOUT)
---
...
box_error = lerror.box(err)
---
...
tostring(box_error)
---
- '{"type":"ClientError","code":78,"message":"Timeout exceeded","trace":[{"file":"[C]","line":4294967295}]}'
...
vshard_error = lerror.vshard(lerror.code.UNREACHABLE_MASTER, {uuid = 'uuid', reason = 'reason'}, 'message 1 2 3')
---
...
tostring(vshard_error)
---
- '{"reason":"reason","code":11,"type":"ShardingError","uuid":"uuid","message":"message
  1 2 3"}'
...
log = require('log')
---
...
log.info('Log error: %s', vshard_error)
---
...
test_run:grep_log('default', '"reason":"reason","code":11,"type":"ShardingError"')
---
- '"reason":"reason","code":11,"type":"ShardingError"'
...
function raise_lua_err() assert(false) end
---
...
ok, err = pcall(raise_lua_err)
---
...
lerror.make(err)
---
- type: ClientError
  code: 32
  message: '[string "function raise_lua_err() assert(false) end "]:1: assertion failed!'
  trace:
  - file: '[C]'
    line: 4294967295
...
